### PR TITLE
Mention requiring the gem in the README

### PR DESCRIPTION
**Pull request by mcary**
@flavorjones here is a PR for Issue #66 in case that is helpful.  I'm happy to make adjustments if desired.

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
:+1: Definitely would have saved me about 10 minutes just now ;)

**Comment by brauliomartinezlm** [comment]
Same for me. Lost time figuring this out. Please add this to the README

**Comment by flavorjones** [comment]
Thanks for submitting this PR and apologies for taking so long to see it and merge it.

**Comment by mcary** [comment]
Thanks!  👍

**Pull request merged**
