### PR TITLE
Allow setting version

### PR DESCRIPTION
**Pull request by jonny5**
- Add ability to configure version (updated README to reflect)
- Store the version in a `.chromedriver-version` file and use that to determine which version to run

I was running into issues where I wanted to run a different version of `chromedriver` locally and on our CI environment. See #24 for more context.

### CODE REVIEW

**Comment by jonny5** [comment]
@flavorjones would be great to get your thoughts on merging this

**Comment by Lordnibbler** [comment]
@flavorjones can we get this merged please? 🙏

**Comment by swelther** [comment]
I could use this feature too. Any news on this? Would be really nice to have it.

**Comment by flavorjones** [comment]
Sorry all! Somehow I missed this when it was submitted (was taking a break from OSS at the time).

This looks good. Let me kick the tires and I expect to merge it and cut a release today.

**Comment by flavorjones** [comment]
@jonny5 The location of the `.chromedriver-version` file feels strange to me.

On my system, because I use RVM, the `helper.rb` file is installed at `/home/flavorjones/.rvm/gems/ruby-2.4.0/gems/chromedriver-helper-1.0.0/lib/chromedriver/helper.rb`. So this file would be stored in `~/.rvm/gems/ruby-2.4.0/gems/chromedriver-helper-1.0.0/lib`. This feels weird, as it's now specific to the combination of ruby version and gem version. Wouldn't it be a universal value for a system regardless of ruby version or gem version?

For system ruby users, it's even stranger. The gem gets installed at  `/var/lib/gems/2.3.0/gems/chromedriver-helper-1.0.0/lib/chromedriver/helper.rb` meaning that the version file is saved at `/usr/lib/ruby/gems/2.3.0/gems/chromedriver-helper-1.0.0/lib`, but:

```
$ ls -l /var/lib/gems/2.3.0/gems/chromedriver-helper-1.0.0/lib
total 4
drwxr-xr-x 3 root root 4096 2017-01-04 13:42 chromedriver/
```

meaning that I can't call `Chromedriver.set_version` without running my process as root.

Can I ask to step back and examine what workflow we want to support? This seems odd to me.

(Sorry I didn't bring all this up sooner.)

**Comment by flavorjones** [comment]
Would you be open to storing this information in the `~/.chromedriver-helper` directory?

**Comment by swelther** [comment]
Any news on this? Would be nice to get this released with config in the home directory :wink:

**Comment by akang2u** [comment]
@jonny5 +1 ^^

**Comment by jasonhuntrods** [comment]
+1

**Comment by jonny5** [comment]
my bad, wasn't receiving notifications on this for some reason. 

@flavorjones storing in `chromedriver-helper` directory is sane to me, I should be able to make the update this weekend.

**Comment by jonny5** [comment]
@flavorjones updated

**Comment by jonny5** [comment]
@flavorjones any update here?

**Comment by flavorjones** [comment]
Merged manually. Cutting a release tonight if I can.

**Comment by flavorjones** [comment]
Just shipped v1.1.0. Sorry for the long wait, and thanks for your patience and the great PR.

**Comment by jonny5** [comment]
@flavorjones 👍  no worries, thanks for maintaining this!

**Pull request closed without merging**
